PyDjango/blog/urls.py
from django.urls import path

from .views import *



app_name = 'blog'
urlpatterns = [

    # Example: /
    path('', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    path('post/', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    path('archive/', PostAV.as_view(), name='post_archive'),

    # Example: /archive/2012/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),

    # Example: /archive/2012/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),

    # Example: /archive/2012/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),

    # Example: /archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    path('tag/', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    path('search/', SearchFormView.as_view(), name='search'),

    # Example: /add/
    path('add/',
         PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         PostDeleteView.as_view(), name="delete",
    ),
]

PyDjango/bookmark/urls.py
from django.urls import path

from .views import *



app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),

    # Example: /add/
    path('add/',
         BookmarkCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         BookmarkChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         BookmarkUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         BookmarkDeleteView.as_view(), name="delete",
    ),
]

PyDjango/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PyDjango/photo/urls.py
from django.urls import path

from .views import *



app_name = 'photo'
urlpatterns = [

    # Example: /
    path('', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    path('album/', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    path('album/add/',
         AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    path('album/change/',
         AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    path('album/<int:pk>/update/',
         AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    path('album/<int:pk>/delete/',
         AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    path('photo/add/',
         PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    path('photo/change/',
         PhotoChangeLV.as_view(), name="photo_change",
         ),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/',
         PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/',
         PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

PyDjango/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
    {% if user.is_active %}
    <h4 class="welcome">Welcome,
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous /
                <a href="{% url 'login' %}">Login</a> /
                <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>

    <li>Add&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Post</a></li>
            <li><a href="{% url 'photo:album_add' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
        </ul>
    </li>
    <li>Change&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Post</a></li>
            <li><a href="{% url 'photo:album_change' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

PyDjango/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i><b></td>
        <td>You can store your own bookmarks by Bookmark application. It's also possible to update or delete your bookmarks.</td>
        <td class="Edit"><i><a href="{% url 'bookmark:add' %}">Add</a></i></td>
        <td class="Edit"><i><a href="{% url 'bookmark:change' %}">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i><b></td>
        <td>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.</td>
        <td class="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
        <td class="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'photo:index' %}">Photo</a></i><b></td>
        <td>You can upload your own photos through this application. If you delete an album, all photos within it will be deleted.</td>
        <td class="Edit"><i><a href="{% url 'photo:album_add' %}">Add</a></i></td>
        <td class="Edit"><i><a href="{% url 'photo:album_change' %}">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; shkim 2016
</div>
{% endblock footer %}