PyDjango/blog/urls.py
from django.urls import path

from .views import *



app_name = 'blog'
urlpatterns = [

    # Example: /
    path('', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    path('post/', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    path('archive/', PostAV.as_view(), name='post_archive'),

    # Example: /archive/2012/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),

    # Example: /archive/2012/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),

    # Example: /archive/2012/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),

    # Example: /archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    path('tag/', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    path('search/', SearchFormView.as_view(), name='search'),

    # Example: /add/
    path('add/',
         PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         PostDeleteView.as_view(), name="delete",
    ),
]

PyDjango/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PyDjango/photo/urls.py
from django.urls import path

from .views import *



app_name = 'photo'
urlpatterns = [

    # Example: /
    path('', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    path('album/', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    path('album/add/',
         AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    path('album/change/',
         AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    path('album/<int:pk>/update/',
         AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    path('album/<int:pk>/delete/',
         AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    path('photo/add/',
         PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    path('photo/change/',
         PhotoChangeLV.as_view(), name="photo_change",
         ),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/',
         PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/',
         PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

PyDjango/photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from .fields import ThumbnailImageField



class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

PyDjango/photo/forms.py
from django.forms.models import inlineformset_factory

from .models import Album, Photo



PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

PyDjango/photo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Album, Photo



class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo


#--- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUpdateView(LoginRequiredMixin, UpdateView) :
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')


class PhotoDeleteView(LoginRequiredMixin, DeleteView) :
    model = Photo
    success_url = reverse_lazy('photo:index')


#--- Add/Change/Update/Delete for Album
#--- Change/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)


class AlbumDeleteView(LoginRequiredMixin, DeleteView) :
    model = Album
    success_url = reverse_lazy('photo:index')


#--- InlineFormSet View
#--- Add/Update for Album
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet


class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('photo:album_detail', pk=self.object.id)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

PyDjango/photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Album Change - {{user}}</h1>
    
    <table class="change-list">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

PyDjango/photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Album Delete</h1>

    <form action="." method="post"> {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

PyDjango/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

PyDjango/photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}album_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Album-Photo InlineFormSet</h1>

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
    {% endif %}
    {% if formset.errors %}
    <p class="errornote">Wrong! Please correct the FORMSET error(s) below.</p>
    {% endif %}


    <h4>Create or Update Album contents.</h4>

    <fieldset class="aligned">
        <div class="form-row">
            {{ form.name.label_tag }} {{ form.name }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>

    <h4>Create or Update Photo contents.</h4>

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
    <fieldset class="aligned">
        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>
    {% endfor %}

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_name').focus();</script>

    </form>

</div>
{% endblock %}

PyDjango/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
    </div>

    <hr/>

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>
{% endblock %}

PyDjango/photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Photo Change - {{user}}</h1>
    
    <table class="change-list">
        <tr>
            <th>Album</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td>{{ item.album }}</td>
            <td>{{ item.title }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

PyDjango/photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Photo Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

PyDjango/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2>{{ object.title }}</h2>
    
    <table class="photo-detail">
    <tr>
    <td>
        <a href="{{ object.image.url }}">
        <img style="max-width:100%" src="{{ object.image.url }}" />
        </a>
    </td>
    
    <td>
    <ul>
        <li>Photo Description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>{% endif %}
        <li>Date Uploaded</li>
        <p>{{ object.upload_date }}</p>
        <li>Album Name</li>
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
    </ul>
    </td>
    </tr></table>

</div>
{% endblock %}

PyDjango/photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}photo_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Photo Create/Update - {{user}}</h1>

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your photo.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>

        <div class="form-row">
            {{ form.album.label_tag }} {{ form.album }}
            <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a></button>
        </div>
    
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_album').focus();</script>

    </form>

</div>
{% endblock %}